services:
  web:
    build: .
    container_name: website
    volumes:
      - ./website:/var/www/html
      - ./log/apache:/var/log/apache2
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: site
      DATABASE_USER: root
      DATABASE_PASSWORD: admin
    depends_on:
      - db
    networks:
      network:
        ipv4_address: 10.10.10.2

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: site
    volumes:
      - db_data:/var/lib/mysql
    networks:
      network:
        ipv4_address: 10.10.10.3

volumes:
  db_data: {}

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24